apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipinfo-deployment
spec:
  selector:
    matchLabels:
      app: ipinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: ipinfo
    spec:
      containers:
      - name: ipinfo
        image: {{image_here}}
        ports:
        - containerPort: 5000